---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: / ## disables post output
timezone: Europe/Stockholm
lsi: false
markdown: kramdown
highlighter: pygments


### content configuration ###
title:       "Smart Norrköping"
keywords:    "Smart City, Norrköping, HiQ, Smart, Intelligent, Heart, City, Peking"
description: "Developing the digital heart and pulse of Sweden's most innovative city."
source_link: 
favicon:     #put a path like: "img/favicon.ico"
touch_icon:  #put a path like: "img/apple-touch-icon.png"
google_analytics_key: UA-61325538-2


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  pink:      '#f2385a'
  blue:     '#3aa1bf'
  green:    '#45aba1'
  orange:    '#f5a503'
  