---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: / ## disables post output
timezone: null
lsi: false
markdown: kramdown
highlighter: pygments


### content configuration ###
title:       "Tigris consulting"
keywords:    "Tigris, commercial, consulting, "
description: "Tigris commercial société de recrutement et de formation de commercial"
source_link: ""
favicon:     "img/favicon.ico"
touch_icon:  "img/apple-touch-icon.png"
google_analytics_key: UA-49607422-1 ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#101E21'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  gray:    	 '#262A2B'
  orange:    '#fab125'
  turquoise: '#0fbfcf'
  bleu1: 	 '#BDD7D8'
  bleu2: 	 '#588B8E'
  bleu3: 	 '#1A4A54'
  bleu4: 	 '#11343A'
  
  

kramdown:
  auto_ids:  false

